'use client';
import {useEffect,useRef,useState} from 'react';
type ApiResult={error?:string;state:State;code?:string;token?:string;left?:boolean;resume?:{code:string;token:string;name:string};correct?:boolean};
type Player={id:string;name:string;score:number;correct:boolean};type State={revision:number;code:string;host:string;players:Player[];self:string;phase:string;round:number;total:number;category:string;options:string[];title?:string;clues:string[];endsAt:number;giver:string;giverName?:string;order:string[];names?:Record<string,string>;lastScores?:Record<string,number>};
const categories=['迪士尼電影','動畫電影','恐怖電影','經典與科幻','混合類別'];
const emojiGroups:Record<string,string[]>={
 '表情':['😀','😂','🥹','😍','😎','😭','😱','😴','🤔','🤫','😈','👻','🤖','💀','🥳','😡','😇','🥶','🤠','👽'],
 '人物':['👶','👧','👦','👩','👨','👸','🤴','🧙','🧚','🦸','🦹','🧛','🧟','🕵️','👮','👩‍🚀','👨‍🍳','🧑‍🎤','💃','🕺'],
 '動物':['🦁','🐯','🐻','🐼','🐨','🐰','🐭','🐱','🐶','🐺','🦊','🐸','🐉','🦄','🦈','🐟','🐍','🦋','🦖','🐒'],
 '場景':['🏰','🏠','🏙️','🌃','🏝️','🌊','🌋','🏔️','🌳','🌹','❄️','☀️','🌙','⭐','🌈','🔥','⚡','💧','🌪️','🪐'],
 '物品':['👑','💍','🗡️','🪄','📖','🧸','🎁','🎈','🎭','🎬','🎮','🎵','🎤','🎸','🧪','🔑','🚪','⏰','🕯️','💎'],
 '交通':['🚗','🚕','🚓','🚀','🛸','✈️','🚢','🚂','🚲','🛶','🏎️','🚁','🛹','🚑','🚎'],
 '符號':['❤️','💔','💖','💥','💤','💬','❓','❗','✅','❌','👀','👣','🙌','👍','👎','🎯','🏆','🔍','➡️','♾️']
};
function EmojiComposer({value,onChange,label,compact=false}:{value:string;onChange:(v:string)=>void;label:string;compact?:boolean}){
 const [open,setOpen]=useState(false),[group,setGroup]=useState('表情');const input=useRef<HTMLTextAreaElement>(null);
 function insert(emoji:string){const el=input.current,start=el?.selectionStart??value.length,end=el?.selectionEnd??value.length;const next=value.slice(0,start)+emoji+value.slice(end);if(next.length>100)return;onChange(next);requestAnimationFrame(()=>{el?.focus();el?.setSelectionRange(start+emoji.length,start+emoji.length)})}
 return <div className="field"><label htmlFor={compact?'extra-clue':'clue'}>{label}</label><textarea ref={input} id={compact?'extra-clue':'clue'} value={value} maxLength={100} onChange={e=>onChange(e.target.value)} placeholder="例如 🦁👑" className={compact?'compact-input':''}/><button type="button" className="secondary emoji-toggle" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'收起 emoji':'😀 選擇 emoji'}</button>{open&&<div className="emoji-picker"><div className="emoji-tabs" role="group" aria-label="emoji 類別">{Object.keys(emojiGroups).map(x=><button type="button" key={x} className={group===x?'active':''} onClick={()=>setGroup(x)}>{x}</button>)}</div><div className="emoji-options" role="group" aria-label={`${group} emoji`}>{emojiGroups[group].map((e,i)=><button type="button" key={`${e}-${i}`} onClick={()=>insert(e)} aria-label={`加入 ${e}`}>{e}</button>)}</div></div>}</div>
}
export default function Game(){const [identity,setIdentity]=useState<{code:string;token:string}|null>(null),[state,setState]=useState<State|null>(null),[name,setName]=useState(''),[code,setCode]=useState(''),[clue,setClue]=useState(''),[guess,setGuess]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[clock,setClock]=useState(Date.now()),[lastWrong,setLastWrong]=useState(false);
 const inflight=useRef(false);
 function acceptState(incoming:State){setState(previous=>previous&&previous.code===incoming.code&&previous.self===incoming.self&&previous.revision>incoming.revision?previous:incoming)}
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('emoji-cinema-session')||'null');if(x?.code&&x?.token)setIdentity(x)}catch{}},[]);
 useEffect(()=>{if(!identity)return;let active=true;let polling=false;const poll=async()=>{if(polling)return;polling=true;try{const r=await fetch(`/api/game?code=${encodeURIComponent(identity.code)}&token=${encodeURIComponent(identity.token)}`,{cache:'no-store'}),j=await r.json() as ApiResult;if(!active)return;if(r.ok){acceptState(j.state);setError(previous=>previous==='連線中斷，正在重試…'?'':previous)}else if(r.status===403||r.status===404){localStorage.removeItem('emoji-cinema-session');setIdentity(null);setState(null);setError(j.error||'無法載入房間')}else setError(j.error||'操作失敗')}catch{if(active)setError('連線中斷，正在重試…')}finally{polling=false}};poll();const interval=setInterval(poll,1200);return()=>{active=false;clearInterval(interval)}},[identity]);
 useEffect(()=>{const t=setInterval(()=>setClock(Date.now()),250);return()=>clearInterval(t)},[]);
 async function act(action:string,more:Record<string,unknown>={}){if(inflight.current)return;inflight.current=true;setBusy(true);setError('');try{let resumeToken: string|undefined;if(action==='enter'){try{const saved=JSON.parse(localStorage.getItem('emoji-cinema-return')||'null');if(saved?.code===String(more.code||'').trim().toUpperCase()&&saved?.name?.toLocaleLowerCase()===String(more.name||'').trim().toLocaleLowerCase())resumeToken=saved.token}catch{}}const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...identity,...more,resumeToken})}),j=await r.json() as ApiResult;if(!r.ok)throw Error(j.error||'操作失敗');if(j.left){if(j.resume){localStorage.setItem('emoji-cinema-return',JSON.stringify(j.resume));setCode(j.resume.code);setName(j.resume.name)}localStorage.removeItem('emoji-cinema-session');setIdentity(null);setState(null);return}if(j.code&&j.token){const id={code:j.code,token:j.token};localStorage.setItem('emoji-cinema-session',JSON.stringify(id));localStorage.removeItem('emoji-cinema-return');setIdentity(id)}acceptState(j.state);if(action==='guess'){setLastWrong(!j.correct);setGuess('')}if(action==='clue')setClue('');if(action==='again'){setClue('');setGuess('');setLastWrong(false)}}catch(e){setError(e instanceof Error?e.message:'操作失敗')}finally{inflight.current=false;setBusy(false)}}
 const me=state?.players.find(p=>p.id===state.self);
 const giverName=state?.giverName||state?.players.find(p=>p.id===state.giver)?.name;
 const isGiver=state?.self===state?.giver,isHost=state?.self===state?.host;
 const remain=Math.max(0,Math.ceil(((state?.endsAt||0)-clock)/1000));
 const leaderboard=state?[...state.players].sort((a,b)=>b.score-a.score):[];
 const winnerScore=leaderboard[0]?.score;
 const winners=leaderboard.filter(p=>p.score===winnerScore).map(p=>p.name).join('、');
 const phaseLabel:Record<string,string>={lobby:'等待室',choose:'選片中',clue:'準備線索',guess:'搶答中',reveal:'本回合結算',finished:'最終結果'};
 const playerStatus=(p:Player)=>state?.phase==='lobby'?(p.id===state.host?'房主 · 已加入':'已加入'):state?.phase==='guess'?(p.id===state.giver?'出題中':p.correct?'已猜對':'猜題中'):p.id===state?.giver&&state?.phase!=='finished'?'本回合出題者':p.id===state?.host?'房主':'在線';
 return <main className="shell"><div className="wrap">
  <header className="top"><div className="brand"><span className="brand-mark" aria-hidden="true">✦</span><span>EMOJI <b>CINEMA</b></span></div><span className="brand-caption">一場用表情演出的電影之夜</span></header>
  {!state?<div className="home-layout"><section className="panel home-panel">
   <span className="eyebrow">THE MOVIE GUESSING PARTY</span><h1>用 emoji 出題。<br/><em>讓朋友猜電影。</em></h1><p className="lede">各自拿出手機，輸入房間碼就能一起玩。</p>
   <div className="field"><label htmlFor="name">你的暱稱</label><input id="name" maxLength={18} value={name} onChange={e=>setName(e.target.value)} placeholder="例如：電影迷" autoComplete="nickname"/></div>
   <button className="primary full" disabled={busy} onClick={()=>act('create',{name})}>{busy?'處理中…':'建立房間'}</button>
   <div className="divider"><span>已有房間碼？</span></div>
   <div className="field"><label htmlFor="code">五位房間碼</label><input id="code" className="room-input" maxLength={5} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="輸入房間碼" autoCapitalize="characters"/></div>
   <button className="secondary full" disabled={busy} onClick={()=>act('enter',{name,code})}>{busy?'處理中…':'加入朋友的房間'}</button>
  </section><aside className="rules-panel"><span className="eyebrow">HOW TO PLAY</span><h2>今晚，誰最懂電影？</h2><ol className="steps"><li>輪流私下選電影，用 emoji 給線索。</li><li>其他玩家有 75 秒搶答，越早猜對分數越高。</li><li>每人出題兩次，總分最高者勝出。</li></ol><div className="rule-foot">2–8 位玩家 · 每人一台裝置</div></aside></div>:
  <><div className="session-bar"><span className="session-code">房間 <strong>{state.code}</strong></span><span className="session-phase">{phaseLabel[state.phase]}</span><span className="session-round">{state.phase==='lobby'?'準備開玩':`第 ${Math.min(state.round+1,state.total||1)} / ${state.total||'—'} 回合`}</span></div>
   <div className="game-layout"><section className="panel play-panel">
    {state.phase==='lobby'&&<div className="phase-content"><span className="eyebrow">YOUR ROOM IS READY</span><h1>大家都進來了嗎？</h1><p className="lede">分享房間碼，朋友加入後會立即出現在右側名單。</p><div className="ticket"><span className="ticket-label">ROOM CODE</span><strong>{state.code}</strong><span className="ticket-note">在同一個網址輸入這組代碼</span></div><div className="action-row"><button className="secondary" onClick={()=>navigator.clipboard?.writeText(location.href)}>複製遊戲網址</button>{isHost&&<button className="primary" disabled={busy||state.players.length<2} onClick={()=>act('start')}>{busy?'處理中…':'開始遊戲'}</button>}</div>{isHost&&state.players.length<2&&<p className="helper">至少需要兩位玩家才能開始。</p>}{!isHost&&<div className="feedback waiting" role="status">已加入房間，等待房主開始遊戲。</div>}<button className="text-button" disabled={busy} onClick={()=>act('leave')}>退出房間並換玩家</button></div>}
    {state.phase==='choose'&&<div className="phase-content"><span className="eyebrow">PICK A MOVIE · {giverName}</span><h1>{isGiver?'今晚想演哪一部？':'正在挑選電影'}</h1>{isGiver?<><p className="lede">選擇類別，再挑一部電影。片名只有你看得到。</p><div className="field"><label htmlFor="category">電影類別</label><select id="category" value={state.category} onChange={e=>act('category',{category:e.target.value})}><option value="">選擇類別</option>{categories.map(x=><option key={x}>{x}</option>)}</select></div>{state.options.length>0&&<div className="choices" aria-label="候選電影">{state.options.map(x=><button className="choice" key={x} disabled={busy} onClick={()=>act('pick',{title:x})}>{x}<span aria-hidden="true">↗</span></button>)}</div>}</>:<div className="feedback waiting" role="status">{giverName} 正在選片，請稍候。</div>}</div>}
    {state.phase==='clue'&&<div className="phase-content"><span className="eyebrow">SET THE SCENE · {giverName}</span><h1>{isGiver?'用 emoji 演出這部電影':'線索即將登場'}</h1>{isGiver?<><div className="secret-title"><span>你的電影</span><strong>{state.title}</strong></div><p className="lede">只能用 emoji 與符號。送出第一條線索，75 秒倒數就會開始。</p><EmojiComposer value={clue} onChange={setClue} label="emoji 線索"/><button className="primary" disabled={busy} onClick={()=>act('clue',{clue})}>{busy?'送出中…':'送出線索，開始計時'}</button></>:<div className="feedback waiting" role="status">{giverName} 正在準備第一條線索。</div>}</div>}
    {state.phase==='guess'&&<div className="phase-content guess-phase"><div className="round-head"><div><span className="eyebrow">GUESS THE MOVIE</span><h1>這是哪部電影？</h1></div><span className={`timer ${remain<=15?'timer-urgent':''}`} aria-label={`剩餘 ${remain} 秒`}><small>剩餘</small>{remain}<small>秒</small></span></div><div className="emoji" aria-label="emoji 線索">{state.clues.join('　')}</div>{isGiver?<><div className="feedback waiting">答案是 <strong>{state.title}</strong>。大家正在搶答。</div><EmojiComposer value={clue} onChange={setClue} label="補充 emoji 線索" compact/><button className="secondary" disabled={busy} onClick={()=>act('clue',{clue})}>{busy?'送出中…':'補充線索'}</button></>:me?.correct?<div className="feedback success" role="status"><strong>猜對了！</strong><span>等其他玩家作答或倒數結束。🤫</span></div>:<><form className="guess-form" onSubmit={e=>{e.preventDefault();act('guess',{guess})}}><label htmlFor="movie-guess">你的答案</label><div className="guess-controls"><input id="movie-guess" value={guess} maxLength={80} onChange={e=>{setGuess(e.target.value);setLastWrong(false)}} placeholder="輸入中文或英文片名" autoComplete="off"/><button className="primary" disabled={busy||!guess.trim()}>{busy?'送出中…':'送出答案'}</button></div></form>{lastWrong&&<div className="feedback incorrect" role="status">還沒猜對，換個片名再試試。</div>}</>}</div>}
    {state.phase==='reveal'&&<div className="phase-content result-phase"><span className="eyebrow">ROUND {state.round+1} · REVEAL</span><h1>答案揭曉</h1><div className="reveal-title">{state.title}</div><p className="lede">{state.order.length?`本回合 ${state.order.length} 人猜對。`:'這回合沒有人猜對。'}</p><div className="result-list">{state.order.map((id,i)=><div className="result-item" key={id}><span><small>第 {i+1} 名</small>{state.names?.[id]}</span><strong>+{state.lastScores?.[id]}</strong></div>)}<div className="result-item giver-result"><span><small>出題者</small>{giverName}</span><strong>+{state.lastScores?.[state.giver]||0}</strong></div></div>{isHost?<button className="primary result-cta" disabled={busy} onClick={()=>act('next')}>{busy?'處理中…':state.round+1>=state.total?'查看最終結果':'下一回合'}</button>:<div className="feedback waiting" role="status">等待房主進入下一回合。</div>}</div>}
    {state.phase==='finished'&&<div className="phase-content final-phase"><span className="eyebrow">THAT’S A WRAP</span><div className="trophy" aria-hidden="true">🏆</div><h1>今晚的電影王</h1><p className="winner-name">{winners}</p><p className="lede">全部回合完成，謝謝大家一起玩！</p><div className="final-list" aria-label="最終排行榜">{leaderboard.map((p,i)=><div className={`rank-item ${i===0?'first':''}`} key={p.id}><span className="rank-number">{String(i+1).padStart(2,'0')}</span><span className="rank-name">{p.name}{p.id===state.self?'（你）':''}</span><strong>{p.score} 分</strong></div>)}</div>{isHost?<><p className="helper">再玩一局會重設分數，並回到等待室。</p><button className="primary result-cta" disabled={busy} onClick={()=>act('again')}>{busy?'處理中…':'再玩一局'}</button></>:<div className="feedback waiting" role="status">等待房主決定是否再玩一局。</div>}</div>}
    {state.phase!=='lobby'&&<button className="text-button exit-button" disabled={busy} onClick={()=>act('leave')}>退出房間（可用原房間碼返回）</button>}
   </section><aside className="panel roster-panel"><div className="roster-heading"><div><span className="eyebrow">THE CAST</span><h2>玩家與積分</h2></div><span className="player-count">{state.players.length} / 8</span></div><div className="roster-list">{leaderboard.map(p=><div className="roster-player" key={p.id}><span className="avatar" aria-hidden="true">{p.name.charAt(0).toUpperCase()}</span><span className="roster-info"><strong>{p.name}{p.id===state.self?'（你）':''}</strong><small>{playerStatus(p)}</small></span><strong className="score">{p.score}<small>分</small></strong></div>)}</div><div className="scoring"><h3>計分規則</h3><p>先猜對得 100、80、60、40 分；出題者依猜對人數得 0、60、80 或 120 分。每人出題兩次，同分並列。</p></div></aside></div></>}
  {error&&<div className="feedback error global-error" role="alert"><span>{error}</span>{!state&&<button className="text-button" onClick={()=>{localStorage.removeItem('emoji-cinema-session');setIdentity(null);setError('')}}>重新加入</button>}</div>}
 </div></main>
}
