'use client';
import {useEffect,useRef,useState} from 'react';
type ApiResult={error?:string;state:State;code?:string;token?:string;left?:boolean;resume?:{code:string;token:string;name:string};correct?:boolean};
type Player={id:string;name:string;score:number;correct:boolean};type State={revision:number;code:string;host:string;players:Player[];self:string;phase:string;round:number;total:number;category:string;autoPicked?:boolean;options:string[];title?:string;clues:string[];endsAt:number;giver:string;giverName?:string;order:string[];names?:Record<string,string>;lastScores?:Record<string,number>};
const categories:Record<string,string>={'迪士尼電影':'Disney Movies','動畫電影':'Animated Movies','恐怖電影':'Horror Movies','經典與科幻':'Classics & Sci-Fi','混合類別':'All Categories'};
const emojiGroups:Record<string,string[]>={
 'Faces':['😀','😂','🥹','😍','😎','😭','😱','😴','🤔','🤫','😈','👻','🤖','💀','🥳','😡','😇','🥶','🤠','👽'],
 'People':['👶','👧','👦','👩','👨','👸','🤴','🧙','🧚','🦸','🦹','🧛','🧟','🕵️','👮','👩‍🚀','👨‍🍳','🧑‍🎤','💃','🕺'],
 'Animals':['🦁','🐯','🐻','🐼','🐨','🐰','🐭','🐱','🐶','🐺','🦊','🐸','🐉','🦄','🦈','🐟','🐍','🦋','🦖','🐒'],
 'Places':['🏰','🏠','🏙️','🌃','🏝️','🌊','🌋','🏔️','🌳','🌹','❄️','☀️','🌙','⭐','🌈','🔥','⚡','💧','🌪️','🪐'],
 'Objects':['👑','💍','🗡️','🪄','📖','🧸','🎁','🎈','🎭','🎬','🎮','🎵','🎤','🎸','🧪','🔑','🚪','⏰','🕯️','💎'],
 'Travel':['🚗','🚕','🚓','🚀','🛸','✈️','🚢','🚂','🚲','🛶','🏎️','🚁','🛹','🚑','🚎'],
 'Symbols':['❤️','💔','💖','💥','💤','💬','❓','❗','✅','❌','👀','👣','🙌','👍','👎','🎯','🏆','🔍','➡️','♾️']
};
function EmojiComposer({value,onChange,label,compact=false}:{value:string;onChange:(v:string)=>void;label:string;compact?:boolean}){
 const [open,setOpen]=useState(false),[group,setGroup]=useState('Faces');const input=useRef<HTMLTextAreaElement>(null);
 function insert(emoji:string){const el=input.current,start=el?.selectionStart??value.length,end=el?.selectionEnd??value.length;const next=value.slice(0,start)+emoji+value.slice(end);if(next.length>100)return;onChange(next);requestAnimationFrame(()=>{el?.focus();el?.setSelectionRange(start+emoji.length,start+emoji.length)})}
 return <div className="field"><label htmlFor={compact?'extra-clue':'clue'}>{label}</label><textarea ref={input} id={compact?'extra-clue':'clue'} value={value} maxLength={100} onChange={e=>onChange(e.target.value)} placeholder="e.g. 🦁👑" className={compact?'compact-input':''}/><button type="button" className="secondary emoji-toggle" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Hide emoji':'😀 Pick emoji'}</button>{open&&<div className="emoji-picker"><div className="emoji-tabs" role="group" aria-label="Emoji categories">{Object.keys(emojiGroups).map(x=><button type="button" key={x} className={group===x?'active':''} onClick={()=>setGroup(x)}>{x}</button>)}</div><div className="emoji-options" role="group" aria-label={`${group} emoji`}>{emojiGroups[group].map((e,i)=><button type="button" key={`${e}-${i}`} onClick={()=>insert(e)} aria-label={`Add ${e}`}>{e}</button>)}</div></div>}</div>
}
export default function Game(){const [identity,setIdentity]=useState<{code:string;token:string}|null>(null),[state,setState]=useState<State|null>(null),[name,setName]=useState(''),[code,setCode]=useState(''),[clue,setClue]=useState(''),[guess,setGuess]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[clock,setClock]=useState(Date.now()),[lastWrong,setLastWrong]=useState(false);
 const inflight=useRef(false);
 function acceptState(incoming:State){if(incoming.phase==='closed'){localStorage.removeItem('emoji-cinema-session');localStorage.removeItem('emoji-cinema-return');setIdentity(null);setState(null);setError('At least two players are needed to continue. You have been returned to the home screen.');return}setState(previous=>previous&&previous.code===incoming.code&&previous.self===incoming.self&&previous.revision>incoming.revision?previous:incoming)}
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('emoji-cinema-session')||'null');if(x?.code&&x?.token)setIdentity(x)}catch{}},[]);
 useEffect(()=>{if(!identity)return;let active=true;let polling=false;const poll=async()=>{if(polling)return;polling=true;try{const r=await fetch(`/api/game?code=${encodeURIComponent(identity.code)}&token=${encodeURIComponent(identity.token)}`,{cache:'no-store'}),j=await r.json() as ApiResult;if(!active)return;if(r.ok){acceptState(j.state);setError(previous=>previous==='Connection lost. Retrying…'?'':previous)}else if(r.status===403||r.status===404){localStorage.removeItem('emoji-cinema-session');setIdentity(null);setState(null);setError(j.error||'Could not load the room.')}else setError(j.error||'Something went wrong.')}catch{if(active)setError('Connection lost. Retrying…')}finally{polling=false}};poll();const interval=setInterval(poll,1200);return()=>{active=false;clearInterval(interval)}},[identity]);
 useEffect(()=>{const t=setInterval(()=>setClock(Date.now()),250);return()=>clearInterval(t)},[]);
 async function act(action:string,more:Record<string,unknown>={}){if(inflight.current)return;inflight.current=true;setBusy(true);setError('');try{let resumeToken: string|undefined;if(action==='enter'){try{const saved=JSON.parse(localStorage.getItem('emoji-cinema-return')||'null');if(saved?.code===String(more.code||'').trim().toUpperCase()&&saved?.name?.toLocaleLowerCase()===String(more.name||'').trim().toLocaleLowerCase())resumeToken=saved.token}catch{}}const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...identity,...more,resumeToken})}),j=await r.json() as ApiResult;if(!r.ok)throw Error(j.error||'Something went wrong.');if(j.left){if(j.resume){localStorage.setItem('emoji-cinema-return',JSON.stringify(j.resume));setCode(j.resume.code);setName(j.resume.name)}localStorage.removeItem('emoji-cinema-session');setIdentity(null);setState(null);return}if(j.code&&j.token){const id={code:j.code,token:j.token};localStorage.setItem('emoji-cinema-session',JSON.stringify(id));localStorage.removeItem('emoji-cinema-return');setIdentity(id)}acceptState(j.state);if(action==='guess'){setLastWrong(!j.correct);setGuess('')}if(action==='clue')setClue('');if(action==='again'){setClue('');setGuess('');setLastWrong(false)}}catch(e){setError(e instanceof Error?e.message:'Something went wrong.')}finally{inflight.current=false;setBusy(false)}}
 const me=state?.players.find(p=>p.id===state.self);
 const giverName=state?.giverName||state?.players.find(p=>p.id===state.giver)?.name;
 const isGiver=state?.self===state?.giver,isHost=state?.self===state?.host;
 const remain=Math.max(0,Math.ceil(((state?.endsAt||0)-clock)/1000));
 const leaderboard=state?[...state.players].sort((a,b)=>b.score-a.score):[];
 const winnerScore=leaderboard[0]?.score;
 const winners=leaderboard.filter(p=>p.score===winnerScore).map(p=>p.name).join(', ');
 const phaseLabel:Record<string,string>={lobby:'Lobby',choose:'Choosing a movie',clue:'Preparing a clue',guess:'Guessing',reveal:'Round results',finished:'Final results'};
 const playerStatus=(p:Player)=>state?.phase==='lobby'?(p.id===state.host?'Host · Joined':'Joined'):state?.phase==='guess'?(p.id===state.giver?'Giving clues':p.correct?'Guessed correctly':'Guessing'):p.id===state?.giver&&state?.phase!=='finished'?'Clue giver':p.id===state?.host?'Host':'Online';
 return <main className="shell"><div className="wrap">
  <header className="top"><div className="brand"><span className="brand-mark" aria-hidden="true">✦</span><span>EMOJI <b>CINEMA</b></span></div><span className="brand-caption">A movie night in emoji</span></header>
  {!state?<div className="home-layout"><section className="panel home-panel">
   <span className="eyebrow">THE MOVIE GUESSING PARTY</span><h1>Act it out in emoji.<br/><em>Let your friends guess.</em></h1><p className="lede">Grab your own device, enter a room code, and play together.</p>
   <div className="field"><label htmlFor="name">Your nickname</label><input id="name" maxLength={18} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Movie Buff" autoComplete="nickname"/></div>
   <button className="primary full" disabled={busy} onClick={()=>act('create',{name})}>{busy?'Working…':'Create a room'}</button>
   <div className="divider"><span>Already have a room code?</span></div>
   <div className="field"><label htmlFor="code">5-character room code</label><input id="code" className="room-input" maxLength={5} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Enter room code" autoCapitalize="characters"/></div>
   <button className="secondary full" disabled={busy} onClick={()=>act('enter',{name,code})}>{busy?'Working…':'Join a room'}</button>
  </section><aside className="rules-panel"><span className="eyebrow">HOW TO PLAY</span><h2>Who knows movies best?</h2><ol className="steps"><li>Take turns secretly choosing a movie and giving emoji clues.</li><li>Everyone else has 75 seconds to guess. Faster answers earn more points.</li><li>Everyone gives clues twice. The highest score wins.</li></ol><div className="rule-foot">2–8 players · One device each</div></aside></div>:
  <><div className="session-bar"><span className="session-code">Room <strong>{state.code}</strong></span><span className="session-phase">{phaseLabel[state.phase]}</span><span className="session-round">{state.phase==='lobby'?'Ready to play':`Round ${Math.min(state.round+1,state.total||1)} / ${state.total||'—'}`}</span></div>
   <div className="game-layout"><section className="panel play-panel">
    {state.phase==='lobby'&&<div className="phase-content"><span className="eyebrow">YOUR ROOM IS READY</span><h1>Is everyone here?</h1><p className="lede">Share the code. Friends appear in the player list as they join.</p><div className="ticket"><span className="ticket-label">ROOM CODE</span><strong>{state.code}</strong><span className="ticket-note">Enter this code on the same website</span></div><div className="action-row"><button className="secondary" onClick={()=>navigator.clipboard?.writeText(location.href)}>Copy game link</button>{isHost&&<button className="primary" disabled={busy||state.players.length<2} onClick={()=>act('start')}>{busy?'Working…':'Start game'}</button>}</div>{isHost&&state.players.length<2&&<p className="helper">At least two players are needed to start.</p>}{!isHost&&<div className="feedback waiting" role="status">You're in! Waiting for the host to start.</div>}<button className="text-button" disabled={busy} onClick={()=>act('leave')}>Leave room / switch player</button></div>}
    {state.phase==='choose'&&<div className="phase-content"><span className="eyebrow">PICK A MOVIE · {giverName}</span><h1>{isGiver?'Which movie will you act out?':'Choosing a movie'}</h1><p className="helper" role="timer">{remain} seconds to choose · A movie is chosen automatically when time runs out.</p>{isGiver?<><p className="lede">Pick a category and a movie before time runs out. Only you can see the title.</p><div className="field"><label htmlFor="category">Movie category</label><select id="category" value={state.category} onChange={e=>act('category',{category:e.target.value})}><option value="">Choose a category</option>{Object.entries(categories).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>{state.options.length>0&&<div className="choices" aria-label="Movie choices">{state.options.map(x=><button className="choice" key={x} disabled={busy} onClick={()=>act('pick',{title:x})}>{x}<span aria-hidden="true">↗</span></button>)}</div>}</>:<div className="feedback waiting" role="status">{giverName} is choosing a movie. Hang tight.</div>}</div>}
    {state.phase==='clue'&&<div className="phase-content"><span className="eyebrow">SET THE SCENE · {giverName}</span><h1>{isGiver?'Act out this movie in emoji':'A clue is coming'}</h1>{isGiver?<>{state.autoPicked&&<div className="feedback waiting" role="status">Time is up. A movie was chosen for you.</div>}<div className="secret-title"><span>Your movie</span><strong>{state.title}</strong></div><p className="lede">Use only emoji and symbols. The 75-second timer starts with your first clue.</p><EmojiComposer value={clue} onChange={setClue} label="Emoji clue"/><button className="primary" disabled={busy} onClick={()=>act('clue',{clue})}>{busy?'Sending…':'Send clue & start timer'}</button></>:<div className="feedback waiting" role="status">{giverName} is preparing the first clue.</div>}</div>}
    {state.phase==='guess'&&<div className="phase-content guess-phase"><div className="round-head"><div><span className="eyebrow">GUESS THE MOVIE</span><h1>Which movie is it?</h1></div><span className={`timer ${remain<=15?'timer-urgent':''}`} aria-label={`${remain} seconds remaining`}><small>Time</small>{remain}<small>sec</small></span></div><div className="emoji" aria-label="Emoji clue">{state.clues.join('　')}</div>{isGiver?<><div className="feedback waiting">The answer is <strong>{state.title}</strong>. Everyone is guessing.</div><EmojiComposer value={clue} onChange={setClue} label="Additional emoji clue" compact/><button className="secondary" disabled={busy} onClick={()=>act('clue',{clue})}>{busy?'Sending…':'Add clue'}</button></>:me?.correct?<div className="feedback success" role="status"><strong>Correct!</strong><span>Wait for the others or the timer. 🤫</span></div>:<><form className="guess-form" onSubmit={e=>{e.preventDefault();act('guess',{guess})}}><label htmlFor="movie-guess">Your answer</label><div className="guess-controls"><input id="movie-guess" value={guess} maxLength={80} onChange={e=>{setGuess(e.target.value);setLastWrong(false)}} placeholder="Enter the movie title" autoComplete="off"/><button className="primary" disabled={busy||!guess.trim()}>{busy?'Sending…':'Submit guess'}</button></div></form>{lastWrong&&<div className="feedback incorrect" role="status">Not quite. Try another title.</div>}</>}</div>}
    {state.phase==='reveal'&&<div className="phase-content result-phase"><span className="eyebrow">ROUND {state.round+1} · REVEAL</span><h1>The answer is…</h1><div className="reveal-title">{state.title}</div><p className="lede">{state.order.length?`${state.order.length} ${state.order.length===1?'player guessed':'players guessed'} correctly.`:'No one guessed it this round.'}</p><div className="result-list">{state.order.map((id,i)=><div className="result-item" key={id}><span><small>Place {i+1}</small>{state.names?.[id]}</span><strong>+{state.lastScores?.[id]}</strong></div>)}<div className="result-item giver-result"><span><small>Clue giver</small>{giverName}</span><strong>+{state.lastScores?.[state.giver]||0}</strong></div></div>{isHost?<button className="primary result-cta" disabled={busy} onClick={()=>act('next')}>{busy?'Working…':state.round+1>=state.total?'See final results':'Next round'}</button>:<div className="feedback waiting" role="status">Waiting for the host to start the next round.</div>}</div>}
    {state.phase==='finished'&&<div className="phase-content final-phase"><span className="eyebrow">THAT’S A WRAP</span><div className="trophy" aria-hidden="true">🏆</div><h1>Movie night champion</h1><p className="winner-name">{winners}</p><p className="lede">All rounds complete. Thanks for playing!</p><div className="final-list" aria-label="Final leaderboard">{leaderboard.map((p,i)=><div className={`rank-item ${i===0?'first':''}`} key={p.id}><span className="rank-number">{String(i+1).padStart(2,'0')}</span><span className="rank-name">{p.name}{p.id===state.self?' (you)':''}</span><strong>{p.score} pts</strong></div>)}</div>{isHost?<><p className="helper">Playing again resets scores and returns everyone to the lobby.</p><button className="primary result-cta" disabled={busy} onClick={()=>act('again')}>{busy?'Working…':'Play again'}</button></>:<div className="feedback waiting" role="status">Waiting for the host to choose Play Again.</div>}</div>}
    {state.phase!=='lobby'&&<button className="text-button exit-button" disabled={busy} onClick={()=>act('leave')}>Leave room (return with the same code)</button>}
   </section><aside className="panel roster-panel"><div className="roster-heading"><div><span className="eyebrow">THE CAST</span><h2>Players & scores</h2></div><span className="player-count">{state.players.length} / 8</span></div><div className="roster-list">{leaderboard.map(p=><div className="roster-player" key={p.id}><span className="avatar" aria-hidden="true">{p.name.charAt(0).toUpperCase()}</span><span className="roster-info"><strong>{p.name}{p.id===state.self?' (you)':''}</strong><small>{playerStatus(p)}</small></span><strong className="score">{p.score}<small>pts</small></strong></div>)}</div><div className="scoring"><h3>Scoring</h3><p>Correct guesses earn 100, 80, 60, then 40 points. The clue giver earns 0, 60, 80, or 120 based on how many guess correctly. Everyone gives clues twice; ties share a rank.</p></div></aside></div></>}
  {error&&<div className="feedback error global-error" role="alert"><span>{error}</span>{!state&&<button className="text-button" onClick={()=>{localStorage.removeItem('emoji-cinema-session');setIdentity(null);setError('')}}>Join again</button>}</div>}
 </div></main>
}
