import { env } from 'cloudflare:workers';

export const runtime = 'edge';
type Player={id:string;token:string;name:string;score:number;lastSeen?:number;correctAt?:number;guess?:string};
type State={code:string;host:string;players:Player[];departed?:Player[];turns?:string[];giverId?:string;giverName?:string;phase:'lobby'|'choose'|'clue'|'guess'|'reveal'|'finished';round:number;total:number;category:string;options:string[];title:string;clues:string[];endsAt:number;order:string[];lastScores:Record<string,number>};
const BANK:Record<string,{title:string;aliases?:string[]}[]>={
 '迪士尼電影':[{title:'獅子王',aliases:['The Lion King']},{title:'冰雪奇緣',aliases:['Frozen']},{title:'小美人魚',aliases:['The Little Mermaid']},{title:'阿拉丁',aliases:['Aladdin']},{title:'美女與野獸',aliases:['Beauty and the Beast']},{title:'魔髮奇緣',aliases:['Tangled']},{title:'花木蘭',aliases:['Mulan']},{title:'海洋奇緣',aliases:['Moana']},{title:'魔法滿屋',aliases:['Encanto']},{title:'仙履奇緣',aliases:['Cinderella']}],
 '動畫電影':[{title:'玩具總動員',aliases:['Toy Story']},{title:'腦筋急轉彎',aliases:['Inside Out']},{title:'海底總動員',aliases:['Finding Nemo']},{title:'可可夜總會',aliases:['Coco']},{title:'神隱少女',aliases:['Spirited Away']},{title:'功夫熊貓',aliases:['Kung Fu Panda']},{title:'動物方城市',aliases:['Zootopia']},{title:'怪獸電力公司',aliases:['Monsters Inc']},{title:'馴龍高手',aliases:['How to Train Your Dragon']},{title:'超人特攻隊',aliases:['The Incredibles']}],
 '恐怖電影':[{title:'牠',aliases:['It']},{title:'咒',aliases:['Incantation']},{title:'厲陰宅',aliases:['The Conjuring']},{title:'鬼修女',aliases:['The Nun']},{title:'奪魂鋸',aliases:['Saw']},{title:'噤界',aliases:['A Quiet Place']},{title:'鬼娃恰吉',aliases:["Child's Play"]},{title:'逃出絕命鎮',aliases:['Get Out']},{title:'驚聲尖叫',aliases:['Scream']},{title:'陰兒房',aliases:['Insidious']}],
 '經典與科幻':[{title:'鐵達尼號',aliases:['Titanic']},{title:'星際效應',aliases:['Interstellar']},{title:'哈利波特',aliases:['Harry Potter']},{title:'侏羅紀公園',aliases:['Jurassic Park']},{title:'駭客任務',aliases:['The Matrix']},{title:'阿凡達',aliases:['Avatar']},{title:'回到未來',aliases:['Back to the Future']},{title:'蜘蛛人',aliases:['Spider-Man','Spiderman']},{title:'復仇者聯盟',aliases:['The Avengers']},{title:'星際大戰',aliases:['Star Wars']}]
};
const normalize=(s:string)=>s.toLocaleLowerCase().normalize('NFKC').replace(/[\s\p{P}\p{S}]/gu,'');
const db=()=>{if(!env.DB)throw Error('遊戲暫時無法連線，請稍後重試。');return env.DB};
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const problem=(message:string,status=400)=>json({error:message},status);
const TIMEOUT=90000;
function normalizeRoom(s:State){s.departed??=[];s.turns??=Array.from({length:2},()=>s.players.map(p=>p.id)).flat();s.giverId??=s.turns[s.round];s.giverName??=all(s).find(p=>p.id===s.giverId)?.name||'';for(const p of s.players)p.lastSeen??=Date.now()}
function all(s:State){return [...s.players,...(s.departed||[])]}
function actor(s:State,token:string){return s.players.find(p=>p.token===token)}
function current(s:State){return s.players.find(p=>p.id===s.giverId)}
function options(s:State){const pool=s.category==='混合類別'?Object.values(BANK).flat():BANK[s.category];return [...pool].sort(()=>Math.random()-.5).slice(0,5).map(x=>x.title)}
function nextTurn(s:State){while(++s.round<s.total&&!s.players.some(p=>p.id===s.turns?.[s.round])){};if(s.round>=s.total){s.phase='finished';return}s.giverId=s.turns![s.round];s.giverName=all(s).find(p=>p.id===s.giverId)?.name||'';s.phase='choose';s.category='';s.options=[];s.title='';s.clues=[];s.endsAt=0;s.order=[];s.lastScores={};all(s).forEach(p=>{delete p.correctAt;delete p.guess})}
function settle(s:State){if(s.phase!=='guess')return;const n=all(s).filter(p=>p.id!==s.giverId).length,k=s.order.length;s.lastScores={};s.order.forEach((id,i)=>{const pts=i===0?100:i===1?80:i===2?60:40;const p=all(s).find(p=>p.id===id);if(p){p.score+=pts;s.lastScores[id]=pts}});const giver=all(s).find(p=>p.id===s.giverId);const pts=k===0?0:k===n?60:k<=Math.floor(n/2)?120:80;if(giver){giver.score+=pts;s.lastScores[giver.id]=pts}s.phase='reveal';s.endsAt=0}
function depart(s:State,p:Player){s.players=s.players.filter(x=>x.id!==p.id);s.departed!.push(p);if(s.host===p.id)s.host=s.players[0]?.id||'';if(['choose','clue'].includes(s.phase)&&s.giverId===p.id)nextTurn(s);else if(s.phase==='guess'&&s.players.every(x=>x.id===s.giverId||!!x.correctAt))settle(s)}
function sweep(s:State,now:number){let changed=false;for(const p of [...s.players])if(now-(p.lastSeen||now)>TIMEOUT){depart(s,p);changed=true}return changed}
function resume(s:State,p:Player){if(s.players.length>=8)return false;s.departed=s.departed!.filter(x=>x.id!==p.id);p.lastSeen=Date.now();s.players.push(p);if(!s.host)s.host=p.id;return true}
function visible(s:State,p:Player,revision:number){return {revision,code:s.code,host:s.host,players:s.players.map(x=>({id:x.id,name:x.name,score:x.score,correct:!!x.correctAt})),self:p.id,phase:s.phase,round:s.round,total:s.total,category:s.category,options:s.phase==='choose'&&p.id===s.giverId?s.options:[],title:(s.phase==='clue'&&p.id===s.giverId)||['reveal','finished'].includes(s.phase)?s.title:undefined,clues:s.clues,endsAt:s.endsAt,giver:s.giverId,giverName:s.giverName,order:s.order,names:Object.fromEntries(all(s).map(x=>[x.id,x.name])),lastScores:s.phase==='reveal'||s.phase==='finished'?s.lastScores:undefined}}
async function read(code:string){return db().prepare('SELECT version,state FROM rooms WHERE code = ?').bind(code).first<{version:number;state:string}>()}
const retryPause=()=>new Promise(resolve=>setTimeout(resolve,5+Math.random()*20));
async function save(s:State,version:number){return (await db().prepare('UPDATE rooms SET state=?,version=version+1,updated_at=? WHERE code=? AND version=?').bind(JSON.stringify(s),Date.now(),s.code,version).run()).meta.changes}
async function update(code:string,token:string,action:string,data:any){for(let attempt=0;attempt<16;attempt++){const row=await read(code);if(!row)return problem('找不到房間，請檢查房間碼。',404);const s=JSON.parse(row.state) as State;normalizeRoom(s);const now=Date.now();let p=actor(s,token);let changed=false;
 // Polling is also a heartbeat. Persist it sparingly, while still detecting abandoned seats.
 if(action==='join'&&p&&now-(p.lastSeen||0)>10000){p.lastSeen=now;changed=true}
 changed=sweep(s,now)||changed;if(p&&!actor(s,token))p=undefined;
 if(action==='join'&&!p){const old=s.departed!.find(x=>x.token===token);if(old&&resume(s,old)){p=old;changed=true}}
 if(!p)return problem('無法驗證玩家，請用原本的裝置重新加入。',403);
 if(action!=='join'){p.lastSeen=now;changed=true}
 if(s.phase==='guess'&&now>=s.endsAt){settle(s);changed=true}
 if(action==='join'){if(changed){if(!await save(s,row.version)){await retryPause();continue}return json({state:visible(s,p,row.version+1)})}return json({state:visible(s,p,row.version)})}
 if(action==='leave'){if(s.phase==='lobby'){s.players=s.players.filter(x=>x.id!==p.id);if(s.host===p.id)s.host=s.players[0]?.id||'';if(!s.players.length){const result=await db().prepare('DELETE FROM rooms WHERE code=? AND version=?').bind(code,row.version).run();if(result.meta.changes)return json({left:true});await retryPause();continue}}else depart(s,p);if(await save(s,row.version))return json({left:true,resume:s.phase!=='lobby'?{code,token:p.token,name:p.name}:undefined});await retryPause();continue}
 let error='';const isGiver=p.id===s.giverId;
 if(action==='start'){if(s.phase!=='lobby'||s.players.length<2||p.id!==s.host)error='需要房主和至少兩位玩家才能開始。';else{s.phase='choose';s.turns=Array.from({length:2},()=>s.players.map(x=>x.id)).flat();s.total=s.turns.length;s.round=0;s.giverId=s.turns[0];s.giverName=s.players[0].name;s.departed=[]}}
 else if(action==='category'){if(s.phase!=='choose'||!isGiver)error='現在不能選類別。';else{s.category=String(data.category);if(!BANK[s.category]&&s.category!=='混合類別')error='無效的類別。';else s.options=options(s)}}
 else if(action==='pick'){if(s.phase!=='choose'||!isGiver||!s.options.includes(data.title))error='請從候選電影中選一部。';else{s.title=data.title;s.clues=[];s.phase='clue'}}
 else if(action==='clue'){if(!isGiver||!['clue','guess'].includes(s.phase))error='目前無法加入線索。';else{const clue=String(data.clue||'').trim();if(!clue||clue.length>100||/[\p{L}\p{N}]/u.test(clue))error='線索只能包含 emoji 和符號，不能有文字或數字（最多 100 字元）。';else{s.clues.push(clue);if(s.phase==='clue'){s.phase='guess';s.endsAt=now+75000}}}}
 else if(action==='guess'){if(s.phase!=='guess'||isGiver||p.correctAt)error='目前無法作答。';else{const guess=String(data.guess||'').trim().slice(0,80);if(!guess)error='請輸入電影名稱。';else{p.guess=guess;const entry=Object.values(BANK).flat().find(x=>x.title===s.title);if(entry&&[entry.title,...(entry.aliases||[])].some(x=>normalize(x)===normalize(guess))){p.correctAt=now;s.order.push(p.id);if(s.players.every(x=>x.id===s.giverId||!!x.correctAt))settle(s)}}}}
 else if(action==='next'){if(s.phase!=='reveal'||p.id!==s.host)error='只有房主能開啟下一回合。';else nextTurn(s)}
 else if(action==='again'){if(s.phase!=='finished'||p.id!==s.host)error='只有房主能在遊戲結束後開新局。';else{s.phase='lobby';s.round=0;s.total=0;s.turns=[];s.giverId='';s.giverName='';s.category='';s.options=[];s.title='';s.clues=[];s.endsAt=0;s.order=[];s.lastScores={};all(s).forEach(x=>{x.score=0;delete x.correctAt;delete x.guess})}}
 else error='未知操作。';if(error)return problem(error);
 if(await save(s,row.version))return json({state:visible(s,p,row.version+1),correct:action==='guess'?!!p.correctAt:undefined});await retryPause()}
 return problem('剛好有其他玩家同時操作，請再試一次。',409)}
export async function GET(req:Request){try{const u=new URL(req.url),code=(u.searchParams.get('code')||'').toUpperCase(),token=u.searchParams.get('token')||'';if(!/^[A-Z2-9]{5}$/.test(code))return problem('無效房間碼。');return update(code,token,'join',{})}catch(e){console.error(e);return problem('暫時無法讀取遊戲。',500)}}
export async function POST(req:Request){try{const b=await req.json() as any,action=String(b.action||'');if(action==='create'){const name=String(b.name||'').trim().slice(0,18);if(!name)return problem('請輸入暱稱。');const id=crypto.randomUUID(),token=crypto.randomUUID();for(let i=0;i<5;i++){const code=Array.from(crypto.getRandomValues(new Uint8Array(5)),x=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[x%'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'.length]).join('');const s:State={code,host:id,players:[{id,token,name,score:0,lastSeen:Date.now()}],departed:[],turns:[],phase:'lobby',round:0,total:0,category:'',options:[],title:'',clues:[],endsAt:0,order:[],lastScores:{}};try{await db().prepare('INSERT INTO rooms (code,version,state,updated_at) VALUES (?,0,?,?)').bind(code,JSON.stringify(s),Date.now()).run();return json({code,token,state:visible(s,s.players[0],0)})}catch{}}return problem('建立房間失敗，請重試。',500)}
 const code=String(b.code||'').trim().toUpperCase(),token=String(b.token||'');if(!/^[A-Z2-9]{5}$/.test(code))return problem('請輸入五位房間碼。');if(action==='enter'){const name=String(b.name||'').trim().slice(0,18);if(!name)return problem('請輸入暱稱。');for(let i=0;i<16;i++){const row=await read(code);if(!row)return problem('找不到房間。',404);const s=JSON.parse(row.state) as State;normalizeRoom(s);const resumeToken=String(b.resumeToken||'');const old=s.departed!.find(p=>p.token===resumeToken&&p.name.toLocaleLowerCase()===name.toLocaleLowerCase());if(old){if(!resume(s,old))return problem('房間已滿（最多八人）。');if(await save(s,row.version))return json({code,token:old.token,state:visible(s,old,row.version+1)});await retryPause();continue}if(s.phase!=='lobby')return problem('這局已開始；只有原玩家能用此裝置重新加入。');if(s.players.length>=8)return problem('房間已滿（最多八人）。');if(all(s).some(p=>p.name.toLocaleLowerCase()===name.toLocaleLowerCase()))return problem('這個暱稱有人用了。');const id=crypto.randomUUID(),t=crypto.randomUUID(),p={id,token:t,name,score:0,lastSeen:Date.now()};s.players.push(p);if(await save(s,row.version))return json({code,token:t,state:visible(s,p,row.version+1)});await retryPause()}return problem('加入失敗，請再試。',409)}return update(code,token,action,b)
 }catch(e){console.error(e);return problem('操作失敗，請稍後重試。',500)}}
